[pytest]
testpaths = tests features
python_files = test_*.py

addopts =
    -p no:seleniumbase
    --html=reports/report.html
    --self-contained-html
    --screenshot=only-on-failure
    --video=retain-on-failure

log_cli = true
log_cli_level = INFO
log_level = INFO

log_format = %(asctime)s [%(levelname)s] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S

python_functions = test_* scenario_*
